### ISSUE TITLE
Tag crates.io versions

### ISSUE THREAD

**Issue by notpeter** [pearfalse/bitterlemon#3]
I noticed none of the releases on crates.io are tagged. Could you tag them please: 

v0.2.3 21bd7ebfe0b68476cee7041ce6402da439e1a52a
v0.2.2 c89555d08cb93263a138533d5a1e8263ddcda357
v0.2.1 896fbba24a9f5a21b4ec8dad7a1f3379dde3cb48
v0.2.0 b3607efd996a68c814214fbe6e93aab00fa3b694

```
git tag v0.2.3 21bd7ebfe0b68476cee7041ce6402da439e1a52a
git tag v0.2.2 c89555d08cb93263a138533d5a1e8263ddcda357
git tag v0.2.1 896fbba24a9f5a21b4ec8dad7a1f3379dde3cb48
git tag v0.2.0 b3607efd996a68c814214fbe6e93aab00fa3b694
git push --tags
```

**Comment by pearfalse** [comment]
Tags have been pushed as `release/0.2.0` through `release/0.2.3`. Thanks for the prompting.
